var arr = ["If my calculator had a history, it would be more embarrassing than my browser history",
"Everyone was busy, so I went to the movie alone",
"The doll spun around in circles in hopes of coming alive",
"the clouds formed beautiful animals in the sky that eventually created a tornado to wreak havoc",
"It took him a month to finish the meal",
"Please wait outside of the house",
"Giving directions that the mountains are to the west only works when you can see them",
"This made him feel like an old-style rootbeer float smells",
"He waited for the stop sign to turn to a go sign",
"Be careful with that butter knife",
"I've always wanted to go to Tajikistan, but my cat would miss me",
"He had a vague sense that trees gave birth to dinosaurs",
"The virus had powers none of us knew existed",
"We have young kids who often walk into our room at night for various reasons including clowns in the closet",
"Three generations with six decades of life experience",
"When transplanting seedlings, candied teapots will make the task easier",
"She wanted to be rescued, but only if it was Tuesday and raining",
"Don't step on the broken glass",
"Today is the day I'll finally know what brick tastes like",
"The external scars tell only part of the story",
"The shooter says goodbye to his love",
"The father died during childbirth",
"The light in his life was actually a fire burning all around him",
"Today we gathered moss for my uncle's wedding",
"I just wanted to tell you I could see the love you have for your child by the way you look at her",
"Sometimes I stare at a door or a wall and I wonder what is this reality, why am I alive, and what is this all about?",
"He told us a very exciting adventure story",
"She was disgusted he couldn’t tell the difference between lemonade and limeade",
"When he had to picnic on the beach, he purposely put sand in other people’s food",
"He dreamed of eating green apples with worms"]

module.exports = arr 